[build]
functions="/functions"

[redirects]]
  from = "/api/*"
  to = "https://master--cool-gnome-d84e5e.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200